services:
  gears: # docker-compose run gears
    command: /usr/bin/bash # launch a command line to run compiled gears
    image: physino/gears # shorter than physino/geant4:gears
    profiles: [ "gears" ] # https://docs.docker.com/compose/profiles
    platform: linux/amd64 # pre-compiled geant4 is not available for arm64
    volumes: [".:/root/gears"] # No X11 as OGL on docker is hard to set
    build: INSTALL/Docker # docker-compose build gears

  geant4: # docker-compose run geant4
    command: /usr/bin/bash # launch a command line to compile GEARS
    image: geant4/geant4 # https://hub.docker.com/r/geant4/geant4
    profiles: [ "geant4" ]
    environment: # https://docs.docker.com/desktop/networking
      - DISPLAY=host.docker.internal:0.0 # needed for Qt
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # needed for Qt
      - .:/root/gears
    # host.docker.internal doesn't exist in a Linux host
    # https://stackoverflow.com/a/24326540
    # https://stackoverflow.com/questions/70725881
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # https://docs.docker.com/compose/compose-file/#working_dir
    working_dir: /root/gears

  root: # docker-compose run root
    command: /usr/bin/bash # launch a command line to run root
    image: physino/root # https://hub.docker.com/r/physino/root
    profiles: [ "root" ]
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/root/gears
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /root/gears
    build: INSTALL/ROOT/ # docker-compose build root

  # launch a Jupyter notebook service to analyze data with ROOT or Python
  notebook: # docker-compose up
    command: /usr/bin/root --notebook --allow-root --no-browser --ip=0.0.0.0
    image: physino/root:notebook
    ports: [ "8888:8888" ] # only exposed with `up`, not 'run`
    volumes: [".:/root/gears"]
    build: INSTALL/ROOT/notebook # docker-compose build notebook

  heprapp: # docker-compose run heprapp
    command: /usr/bin/hv # launch HepRApp
    image: physino/heprapp # https://hub.docker.com/r/physino/heprapp
    profiles: [ "heprapp" ]
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/root/gears
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # https://github.com/microsoft/WSL/issues/5339#issuecomment-1125709672
    # https://docs.docker.com/compose/compose-file/#sysctls
    sysctls:
      - net.ipv4.tcp_keepalive_intvl=60
      - net.ipv4.tcp_keepalive_probes=5
      - net.ipv4.tcp_keepalive_time=300
    build: tutorials/detector/visualization/ # docker-compose build heprapp

  x3d: # docker-compose up x3d
    # according to https://stackoverflow.com/a/16488110
    # a browser cannot access g4_??.x3d embed in file://g4_??.html
    # a simple web server is needed to avoid change browser settings
    # -u: don't buffer output (https://stackoverflow.com/a/63195558)
    # --cgi: enable CGI (https://stackoverflow.com/a/63195558)
    command: python3 -u -m http.server --cgi
    image: physino/heprapp
    profiles: [ "x3d" ]
    ports: [ "8000:8000" ] # only exposed with `up`, not 'run`
    volumes: [".:/root/gears"]
