services:
  # https://stackoverflow.com/a/65922105
  sh: # docker-compose run sh
    image: physino/gears
    command: /usr/bin/bash
    hostname: Geant4-11.0.1 # https://stackoverflow.com/a/54700656
    # https://gist.github.com/paul-krohn/e45f96181b1cf5e536325d1bdee6c949
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/root/gears
